name: Build RPM

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install RPM build tools
      run: sudo apt-get install -y rpm


    - name: Create RPM build directories
      run: mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}

    - name: Create tarball with correct directory structure
      run: |
        mkdir -p myproject-1.0
        cp update_kernel_params.sh update-proc-params.service myproject-1.0/
        tar czvf myproject-1.0.tar.gz myproject-1.0

    - name: Move files to RPM build directories
      run: |
        mv myproject-1.0.tar.gz ~/rpmbuild/SOURCES/
        mv SPECS/myproject.spec ~/rpmbuild/SPECS/

    - name: Build RPM package
      run: rpmbuild -ba ~/rpmbuild/SPECS/myproject.spec

    - name: Upload RPM package
      uses: actions/upload-artifact@v2
      with:
        name: myproject-rpm
        path: ~/rpmbuild/RPMS/noarch/*.rpm
